name = "filtersheroes"
pages_build_output_dir = "./public"
compatibility_date = "2024-09-15"

[vars]
HUGO_ENV = "production"
HUGO_VERSION = "0.150.0"
GO_VERSION = "1.24"
NODE_VERSION = "22"
PNPM_VERSION = "10.17"
