[[main]]
  name = "Główna"
  pageRef = "/"
  weight = 1

# [[main]]
#   name = "Tagi"
#   pageRef = "/tags/"
#   weight = 40

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/FiltersHeroes/FiltersHeroesWebsite"
  weight = 20

[[social]]
  name = "RSS"
  pre = "fas fa-rss"
  url = "/index.xml"
  weight = 30
